# Generated by Django 3.2.17 on 2023-02-11 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230211_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kursleiter',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='tutor_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Kursleiter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('kurs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kurs')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.AlterField(
            model_name='TutorProfile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='KursleiterProfile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='DozentProfile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
