# Generated by Django 3.2.17 on 2023-02-11 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230211_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dozent',
        ),
        migrations.CreateModel(
            name='Dozent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('titel', models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr')], default='Prof.', max_length=10, verbose_name='Titel')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.AlterField(
            model_name='TutorProfile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='KursleiterProfile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='DozentProfile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
