# Generated by Django 3.2.17 on 2023-02-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230211_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dozent',
            options={'verbose_name_plural': 'Dozenten'},
        ),
        migrations.AlterModelOptions(
            name='kursleiter',
            options={'verbose_name_plural': 'Kursleiter'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name_plural': 'Tutoren'},
        ),
    ]
