# Generated by Django 3.2.17 on 2023-02-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230211_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blatt',
            name='kurs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blatt', to='core.kurs'),
        ),
    ]
